2023-09-03 16:27:00,872 ERROR: Exception on /index [GET] [in C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\app\routes.py", line 30, in index
    posts = current_user.followed_posts().paginate(page, app.config['POSTS_PER_PAGE'], False)
TypeError: Query.paginate() takes 1 positional argument but 4 were given
2023-09-03 16:28:34,728 INFO: Microblog startup [in C:\Mambos\Professional\LaunchIt\flask-tut\microblog\app\__init__.py:46]
2023-09-03 16:28:40,467 ERROR: Exception on /index [GET] [in C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\app\routes.py", line 30, in index
    posts = current_user.followed_posts().paginate(page, app.config['POSTS_PER_PAGE'], False)
TypeError: Query.paginate() takes 1 positional argument but 4 were given
2023-09-03 16:29:29,244 INFO: Microblog startup [in C:\Mambos\Professional\LaunchIt\flask-tut\microblog\app\__init__.py:46]
2023-09-03 16:39:11,244 INFO: Microblog startup [in C:\Mambos\Professional\LaunchIt\flask-tut\microblog\app\__init__.py:46]
2023-09-03 16:40:14,500 INFO: Microblog startup [in C:\Mambos\Professional\LaunchIt\flask-tut\microblog\app\__init__.py:46]
2023-09-03 17:08:34,804 INFO: Microblog startup [in C:\Mambos\Professional\LaunchIt\flask-tut\microblog\app\__init__.py:49]
2023-09-03 17:34:38,091 INFO: Microblog startup [in C:\Mambos\Professional\LaunchIt\flask-tut\microblog\app\__init__.py:49]
2023-09-03 17:35:20,036 ERROR: Exception on /reset_password_request [POST] [in C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\app\routes.py", line 102, in reset_password_request
    send_password_reset_email(user)
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\app\email.py", line 12, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\app\models.py", line 66, in get_reset_password_token
    app.config['SECRET_KEY'], algorithm='HS256').decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
2023-09-03 17:35:49,095 INFO: Microblog startup [in C:\Mambos\Professional\LaunchIt\flask-tut\microblog\app\__init__.py:49]
2023-09-03 17:36:11,857 ERROR: Exception on /reset_password_request [POST] [in C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\app\routes.py", line 102, in reset_password_request
    send_password_reset_email(user)
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\app\email.py", line 16, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',user=user, token=token),
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Mambos\Professional\LaunchIt\flask-tut\microblog\venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.txt
2023-09-03 17:36:48,045 INFO: Microblog startup [in C:\Mambos\Professional\LaunchIt\flask-tut\microblog\app\__init__.py:49]
2023-09-03 17:42:48,770 INFO: Microblog startup [in C:\Mambos\Professional\LaunchIt\flask-tut\microblog\app\__init__.py:49]
2023-09-03 18:14:45,909 INFO: Microblog startup [in C:\Mambos\Professional\LaunchIt\flask-tut\microblog\app\__init__.py:53]
